/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 1.7.0
 *
 * Project: 'HP' 
 * Target:  'HP' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "M55_HP.h"

/* AlifSemiconductor::Device:SOC Peripherals:GPIO:0.9.0 */
#define RTE_Drivers_GPIO   1           /* Driver GPIO */
        /* ----------  Local LPGPIO instance name Aliases  ---------- */
        #define Driver_GPIO15               Driver_GPIOLP
/* AlifSemiconductor::Device:SOC Peripherals:PINCONF:0.9.0 */
#define RTE_Drivers_LL_PINCONF   1           /* Driver PinPAD and PinMux */


#endif /* RTE_COMPONENTS_H */
